# Generated by Django 2.2.12 on 2020-05-24 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(default=False, on_delete='on_delete', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
