# Generated by Django 2.2.12 on 2020-05-24 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_list_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
