# Generated by Django 2.2.12 on 2020-05-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200524_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='creator',
        ),
    ]
